import 'package:islami_app/core/models/sura_data.dart';

abstract class Constants {

  List<String> arabicAuranSuras = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس"
  ];
  List<String> englishQuranSurahs = [
    "Al-Fatiha",
    "Al-Baqarah",
    "Aal-E-Imran",
    "An-Nisa'",
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "At-Tawbah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Ra'd",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Isra",
    "Al-Kahf",
    "Maryam",
    "Ta-Ha",
    "Al-Anbiya",
    "Al-Hajj",
    "Al-Mu'minun",
    "An-Nur",
    "Al-Furqan",
    "Ash-Shu'ara",
    "An-Naml",
    "Al-Qasas",
    "Al-Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajda",
    "Al-Ahzab",
    "Saba",
    "Fatir",
    "Ya-Sin",
    "As-Saffat",
    "Sad",
    "Az-Zumar",
    "Ghafir",
    "Fussilat",
    "Ash-Shura",
    "Az-Zukhruf",
    "Ad-Dukhan",
    "Al-Jathiya",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Adh-Dhariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'a",
    "Al-Hadid",
    "Al-Mujadila",
    "Al-Hashr",
    "Al-Mumtahina",
    "As-Saff",
    "Al-Jumu'a",
    "Al-Munafiqun",
    "At-Taghabun",
    "At-Talaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddathir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat",
    "An-Naba'",
    "An-Nazi'at",
    "Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Inshiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Ghashiyah",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Lail",
    "Ad-Duha",
    "Ash-Sharh",
    "At-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyina",
    "Az-Zalzalah",
    "Al-Adiyat",
    "Al-Qari'a",
    "At-Takathur",
    "Al-Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraysh",
    "Al-Ma'un",
    "Al-Kawthar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas"
  ];
  List<String> AyaNumber = [
    '7',
    '286',
    '200',
    '176',
    '120',
    '165',
    '206',
    '75',
    '129',
    '109',
    '123',
    '111',
    '43',
    '52',
    '99',
    '128',
    '111',
    '110',
    '98',
    '135',
    '112',
    '78',
    '118',
    '64',
    '77',
    '227',
    '93',
    '88',
    '69',
    '60',
    '34',
    '30',
    '73',
    '54',
    '45',
    '83',
    '182',
    '88',
    '75',
    '85',
    '54',
    '53',
    '89',
    '59',
    '37',
    '35',
    '38',
    '29',
    '18',
    '45',
    '60',
    '49',
    '62',
    '55',
    '78',
    '96',
    '29',
    '22',
    '24',
    '13',
    '14',
    '11',
    '11',
    '18',
    '12',
    '12',
    '30',
    '52',
    '52',
    '44',
    '28',
    '28',
    '20',
    '56',
    '40',
    '31',
    '50',
    '40',
    '46',
    '42',
    '29',
    '19',
    '36',
    '25',
    '22',
    '17',
    '19',
    '26',
    '30',
    '20',
    '15',
    '21',
    '11',
    '8',
    '5',
    '19',
    '5',
    '8',
    '8',
    '11',
    '11',
    '8',
    '3',
    '9',
    '5',
    '4',
    '6',
    '3',
    '6',
    '3',
    '5',
    '4',
    '5',
    '6'
  ];

  static List<SuraData> suraDataList = [
    SuraData(id: 1, suraNameAR: "الفاتحه", suraNameEN: "Al-Fatiha", verses: 7),
    SuraData(id: 2, suraNameAR: "البقرة", suraNameEN: "Al-Baqarah", verses: 286),
    SuraData(id: 3, suraNameAR: "آل عمران", suraNameEN: "Aal-E-Imran", verses: 200),
    SuraData(id: 4, suraNameAR: "النساء", suraNameEN: "An-Nisa'", verses: 176),
    SuraData(id: 5, suraNameAR: "المائدة", suraNameEN: "Al-Ma'idah", verses: 120),
    SuraData(id: 6, suraNameAR: "الأنعام", suraNameEN: "Al-An'am", verses: 165),
    SuraData(id: 7, suraNameAR: "الأعراف", suraNameEN: "Al-A'raf", verses: 206),
    SuraData(id: 8, suraNameAR: "الأنفال", suraNameEN: "Al-Anfal", verses: 75),
    SuraData(id: 9, suraNameAR: "التوبة", suraNameEN: "At-Tawbah", verses: 129),
    SuraData(id: 10, suraNameAR: "يونس", suraNameEN: "Yunus", verses: 109),
    SuraData(id: 11, suraNameAR: "هود", suraNameEN: "Hud", verses: 123),
    SuraData(id: 12, suraNameAR: "يوسف", suraNameEN: "Yusuf", verses: 111),
    SuraData(id: 13, suraNameAR: "الرعد", suraNameEN: "Ar-Ra'd", verses: 43),
    SuraData(id: 14, suraNameAR: "إبراهيم", suraNameEN: "Ibrahim", verses: 52),
    SuraData(id: 15, suraNameAR: "الحجر", suraNameEN: "Al-Hijr", verses: 99),
    SuraData(id: 16, suraNameAR: "النحل", suraNameEN: "An-Nahl", verses: 128),
    SuraData(id: 17, suraNameAR: "الإسراء", suraNameEN: "Al-Isra", verses: 111),
    SuraData(id: 18, suraNameAR: "الكهف", suraNameEN: "Al-Kahf", verses: 110),
    SuraData(id: 19, suraNameAR: "مريم", suraNameEN: "Maryam", verses: 98),
    SuraData(id: 20, suraNameAR: "طه", suraNameEN: "Ta-Ha", verses: 135),
    SuraData(id: 21, suraNameAR: "الأنبياء", suraNameEN: "Al-Anbiya", verses: 112),
    SuraData(id: 22, suraNameAR: "الحج", suraNameEN: "Al-Hajj", verses: 78),
    SuraData(id: 23, suraNameAR: "المؤمنون", suraNameEN: "Al-Mu'minun", verses: 118),
    SuraData(id: 24, suraNameAR: "النّور", suraNameEN: "An-Nur", verses: 64),
    SuraData(id: 25, suraNameAR: "الفرقان", suraNameEN: "Al-Furqan", verses: 77),
    SuraData(id: 26, suraNameAR: "الشعراء", suraNameEN: "Ash-Shu'ara", verses: 227),
    SuraData(id: 27, suraNameAR: "النّمل", suraNameEN: "An-Naml", verses: 93),
    SuraData(id: 28, suraNameAR: "القصص", suraNameEN: "Al-Qasas", verses: 88),
    SuraData(id: 29, suraNameAR: "العنكبوت", suraNameEN: "Al-Ankabut", verses: 69),
    SuraData(id: 30, suraNameAR: "الرّوم", suraNameEN: "Ar-Rum", verses: 60),
    SuraData(id: 31, suraNameAR: "لقمان", suraNameEN: "Luqman", verses: 34),
    SuraData(id: 32, suraNameAR: "السجدة", suraNameEN: "As-Sajda", verses: 30),
    SuraData(id: 33, suraNameAR: "الأحزاب", suraNameEN: "Al-Ahzab", verses: 73),
    SuraData(id: 34, suraNameAR: "سبأ", suraNameEN: "Saba", verses: 54),
    SuraData(id: 35, suraNameAR: "فاطر", suraNameEN: "Fatir", verses: 45),
    SuraData(id: 36, suraNameAR: "يس", suraNameEN: "Ya-Sin", verses: 83),
    SuraData(id: 37, suraNameAR: "الصافات", suraNameEN: "As-Saffat", verses: 182),
    SuraData(id: 38, suraNameAR: "ص", suraNameEN: "Sad", verses: 88),
    SuraData(id: 39, suraNameAR: "الزمر", suraNameEN: "Az-Zumar", verses: 75),
    SuraData(id: 40, suraNameAR: "غافر", suraNameEN: "Ghafir", verses: 85),
    SuraData(id: 41, suraNameAR: "فصّلت", suraNameEN: "Fussilat", verses: 54),
    SuraData(id: 42, suraNameAR: "الشورى", suraNameEN: "Ash-Shura", verses: 53),
    SuraData(id: 43, suraNameAR: "الزخرف", suraNameEN: "Az-Zukhruf", verses: 89),
    SuraData(id: 44, suraNameAR: "الدّخان", suraNameEN: "Ad-Dukhan", verses: 59),
    SuraData(id: 45, suraNameAR: "الجاثية", suraNameEN: "Al-Jathiya", verses: 37),
    SuraData(id: 46, suraNameAR: "الأحقاف", suraNameEN: "Al-Ahqaf", verses: 35),
    SuraData(id: 47, suraNameAR: "محمد", suraNameEN: "Muhammad", verses: 38),
    SuraData(id: 48, suraNameAR: "الفتح", suraNameEN: "Al-Fath", verses: 29),
    SuraData(id: 49, suraNameAR: "الحجرات", suraNameEN: "Al-Hujurat", verses: 18),
    SuraData(id: 50, suraNameAR: "ق", suraNameEN: "Qaf", verses: 45),
    SuraData(id: 51, suraNameAR: "الذاريات", suraNameEN: "Adh-Dhariyat", verses: 60),
    SuraData(id: 52, suraNameAR: "الطور", suraNameEN: "At-Tur", verses: 49),
    SuraData(id: 53, suraNameAR: "النجم", suraNameEN: "An-Najm", verses: 62),
    SuraData(id: 54, suraNameAR: "القمر", suraNameEN: "Al-Qamar", verses: 55),
    SuraData(id: 55, suraNameAR: "الرحمن", suraNameEN: "Ar-Rahman", verses: 78),
    SuraData(id: 56, suraNameAR: "الواقعة", suraNameEN: "Al-Waqi'a", verses: 96),
    SuraData(id: 57, suraNameAR: "الحديد", suraNameEN: "Al-Hadid", verses: 29),
    SuraData(id: 58, suraNameAR: "المجادلة", suraNameEN: "Al-Mujadila", verses: 22),
    SuraData(id: 59, suraNameAR: "الحشر", suraNameEN: "Al-Hashr", verses: 24),
    SuraData(id: 60, suraNameAR: "الممتحنة", suraNameEN: "Al-Mumtahina", verses: 13),
    SuraData(id: 61, suraNameAR: "الصف", suraNameEN: "As-Saff", verses: 14),
    SuraData(id: 62, suraNameAR: "الجمعة", suraNameEN: "Al-Jumu'a", verses: 11),
    SuraData(id: 63, suraNameAR: "المنافقون", suraNameEN: "Al-Munafiqun", verses: 11),
    SuraData(id: 64, suraNameAR: "التغابن", suraNameEN: "At-Taghabun", verses: 18),
    SuraData(id: 65, suraNameAR: "الطلاق", suraNameEN: "At-Talaq", verses: 12),
    SuraData(id: 66, suraNameAR: "التحريم", suraNameEN: "At-Tahrim", verses: 12),
    SuraData(id: 67, suraNameAR: "الملك", suraNameEN: "Al-Mulk", verses: 30),
    SuraData(id: 68, suraNameAR: "القلم", suraNameEN: "Al-Qalam", verses: 52),
    SuraData(id: 69, suraNameAR: "الحاقة", suraNameEN: "Al-Haqqah", verses: 52),
    SuraData(id: 70, suraNameAR: "المعارج", suraNameEN: "Al-Ma'arij", verses: 44),
    SuraData(id: 71, suraNameAR: "نوح", suraNameEN: "Nuh", verses: 28),
    SuraData(id: 72, suraNameAR: "الجن", suraNameEN: "Al-Jinn", verses: 28),
    SuraData(id: 73, suraNameAR: "المزّمّل", suraNameEN: "Al-Muzzammil", verses: 20),
    SuraData(id: 74, suraNameAR: "المدّثر", suraNameEN: "Al-Muddathir", verses: 56),
    SuraData(id: 75, suraNameAR: "القيامة", suraNameEN: "Al-Qiyamah", verses: 40),
    SuraData(id: 76, suraNameAR: "الإنسان", suraNameEN: "Al-Insan", verses: 31),
    SuraData(id: 77, suraNameAR: "المرسلات", suraNameEN: "Al-Mursalat", verses: 50),
    SuraData(id: 78, suraNameAR: "النبأ", suraNameEN: "An-Naba'", verses: 40),
    SuraData(id: 79, suraNameAR: "النازعات", suraNameEN: "An-Nazi'at", verses: 46),
    SuraData(id: 80, suraNameAR: "عبس", suraNameEN: "Abasa", verses: 42),
    SuraData(id: 81, suraNameAR: "التكوير", suraNameEN: "At-Takwir", verses: 29),
    SuraData(id: 82, suraNameAR: "الإنفطار", suraNameEN: "Al-Infitar", verses: 19),
    SuraData(id: 83, suraNameAR: "المطفّفين", suraNameEN: "Al-Mutaffifin", verses: 36),
    SuraData(id: 84, suraNameAR: "الإنشقاق", suraNameEN: "Al-Inshiqaq", verses: 25),
    SuraData(id: 85, suraNameAR: "البروج", suraNameEN: "Al-Buruj", verses: 22),
    SuraData(id: 86, suraNameAR: "الطارق", suraNameEN: "At-Tariq", verses: 17),
    SuraData(id: 87, suraNameAR: "الأعلى", suraNameEN: "Al-A'la", verses: 19),
    SuraData(id: 88, suraNameAR: "الغاشية", suraNameEN: "Al-Ghashiyah", verses: 26),
    SuraData(id: 89, suraNameAR: "الفجر", suraNameEN: "Al-Fajr", verses: 30),
    SuraData(id: 90, suraNameAR: "البلد", suraNameEN: "Al-Balad", verses: 20),
    SuraData(id: 91, suraNameAR: "الشمس", suraNameEN: "Ash-Shams", verses: 15),
    SuraData(id: 92, suraNameAR: "الليل", suraNameEN: "Al-Lail", verses: 21),
    SuraData(id: 93, suraNameAR: "الضحى", suraNameEN: "Ad-Duha", verses: 11),
    SuraData(id: 94, suraNameAR: "الشرح", suraNameEN: "Ash-Sharh", verses: 8),
    SuraData(id: 95, suraNameAR: "التين", suraNameEN: "At-Tin", verses: 5),
    SuraData(id: 96, suraNameAR: "العلق", suraNameEN: "Al-Alaq", verses: 19),
    SuraData(id: 97, suraNameAR: "القدر", suraNameEN: "Al-Qadr", verses: 5),
    SuraData(id: 98, suraNameAR: "البينة", suraNameEN: "Al-Bayyina", verses: 8),
    SuraData(id: 99, suraNameAR: "الزلزلة", suraNameEN: "Az-Zalzalah", verses: 8),
    SuraData(id: 100, suraNameAR: "العاديات", suraNameEN: "Al-Adiyat", verses: 11),
    SuraData(id: 101, suraNameAR: "القارعة", suraNameEN: "Al-Qari'a", verses: 11),
    SuraData(id: 102, suraNameAR: "التكاثر", suraNameEN: "At-Takathur", verses: 8),
    SuraData(id: 103, suraNameAR: "العصر", suraNameEN: "Al-Asr", verses: 3),
    SuraData(id: 104, suraNameAR: "الهمزة", suraNameEN: "Al-Humazah", verses: 9),
    SuraData(id: 105, suraNameAR: "الفيل", suraNameEN: "Al-Fil", verses: 5),
    SuraData(id: 106, suraNameAR: "قريش", suraNameEN: "Quraysh", verses: 4),
    SuraData(id: 107, suraNameAR: "الماعون", suraNameEN: "Al-Ma'un", verses: 7),
    SuraData(id: 108, suraNameAR: "الكوثر", suraNameEN: "Al-Kawthar", verses: 3),
    SuraData(id: 109, suraNameAR: "الكافرون", suraNameEN: "Al-Kafirun", verses: 6),
    SuraData(id: 110, suraNameAR: "النصر", suraNameEN: "An-Nasr", verses: 3),
    SuraData(id: 111, suraNameAR: "المسد", suraNameEN: "Al-Masad", verses: 5),
    SuraData(id: 112, suraNameAR: "الإخلاص", suraNameEN: "Al-Ikhlas", verses: 4),
    SuraData(id: 113, suraNameAR: "الفلق", suraNameEN: "Al-Falaq", verses: 5),
    SuraData(id: 114, suraNameAR: "الناس", suraNameEN: "An-Nas", verses: 6),
  ];


}
